name: Publish Release
description: Publish a new release to Github

inputs:
  issuerId:
    description: issuerId
    required: true
  apiKeyId:
    description: apiKeyId
    required: true
  apiPrivateKey:
    description: apiPrivateKey
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup

    - uses: ./.github/actions/cache-packages

    - name: 'Upload app to TestFlight'
      uses: apple-actions/upload-testflight-build@v1
      with:
        app-path: ./apps/safari-extension/dist/archive/Readapt.pkg
        app-type: macos
        issuer-id: ${{ inputs.issuerId }}
        api-key-id: ${{ inputs.apiKeyId }}
        api-private-key: ${{ inputs.apiPrivateKey }}
