export const storageStateV1Fixture = {
  fontFamily: 'inherit',
  fontSize: '200%',
  language: 'en',
  letterSpacing: '2px',
  letters: [
    { active: false, bold: false, key: '1', value: 'b' },
    { active: false, bold: false, key: '2', value: 'd' },
    { active: false, bold: false, key: '3', value: 'p' },
    { active: false, bold: false, key: '4', value: 'q' },
    { active: false, bold: false, key: '5', value: 'k' },
    { active: false, bold: false, key: '6', value: 'c' },
    { active: false, bold: false, key: '7', value: 'n' },
    { active: false, bold: false, key: '8', value: 'm' },
    { active: false, bold: false, key: '9', value: 'v' },
    { active: false, bold: false, key: '10', value: 's' },
    { active: false, bold: false, key: '11', value: 'z' },
    { active: false, bold: false, key: '12', value: 'a' },
    { active: false, bold: false, key: '13', value: 'e' },
    { active: false, bold: false, key: '14', value: 'f' },
    { active: false, bold: false, key: '15', value: 'g' },
    { active: false, bold: false, key: '16', value: 'h' },
    { active: false, bold: false, key: '17', value: 'i' },
    { active: false, bold: false, key: '18', value: 'j' },
    { active: false, bold: false, key: '19', value: 'u' },
    { active: false, bold: false, key: '20', value: 'l' },
    { active: false, bold: false, key: '21', value: 'o' },
    { active: false, bold: false, key: '22', value: 'r' },
    { active: false, bold: false, key: '23', value: 't' },
    { active: false, bold: false, key: '24', value: 'w' },
    { active: false, bold: false, key: '25', value: 'x' },
    { active: false, bold: false, key: '26', value: 'y' }
  ],
  lettersActive: true,
  lineSpacing: 'inherit',
  phonemes: [
    { active: false, bold: false, key: '7', value: 'b' },
    { active: false, bold: false, key: '8', value: 'ch' },
    { active: false, bold: false, key: '9', value: 'd' },
    { active: false, bold: false, key: '10', value: 'dh' },
    { active: false, bold: false, key: '12', value: 'er' },
    { active: false, bold: false, key: '13', value: 'ey' },
    { active: false, bold: false, key: '14', value: 'f' },
    { active: false, bold: false, key: '15', value: 'g' },
    { active: false, bold: false, key: '17', value: 'ih' },
    { active: false, bold: false, key: '18', value: 'iy' },
    { active: false, bold: false, key: '19', value: 'jh' },
    { active: false, bold: false, key: '20', value: 'k' },
    { active: false, bold: false, key: '21', value: 'l' },
    { active: false, bold: false, key: '22', value: 'm' },
    { active: false, bold: false, key: '23', value: 'n' },
    { active: false, bold: false, key: '24', value: 'ng' },
    { active: false, bold: false, key: '27', value: 'p' },
    { active: false, bold: false, key: '28', value: 'r' },
    { active: false, bold: false, key: '29', value: 's' },
    { active: false, bold: false, key: '30', value: 'sh' },
    { active: false, bold: false, key: '31', value: 't' },
    { active: false, bold: false, key: '32', value: 'th' },
    { active: false, bold: false, key: '35', value: 'v' },
    { active: false, bold: false, key: '36', value: 'w' },
    { active: false, bold: false, key: '37', value: 'y' },
    { active: false, bold: false, key: '38', value: 'z' },
    { active: false, bold: false, key: '39', value: 'zh' },
    { active: false, bold: false, key: '1', value: 'aa' },
    { active: false, bold: false, key: '2', value: 'ae' },
    { active: false, bold: false, key: '3', value: 'ah' },
    { active: false, bold: false, key: '4', value: 'ao' },
    { active: false, bold: false, key: '5', value: 'aw' },
    { active: false, bold: false, key: '6', value: 'ay' },
    { active: false, bold: false, key: '11', value: 'eh' },
    { active: false, bold: false, key: '16', value: 'hh' },
    { active: false, bold: false, key: '25', value: 'ow' },
    { active: false, bold: false, key: '26', value: 'oy' },
    { active: false, bold: false, key: '33', value: 'uh' },
    { active: false, bold: false, key: '34', value: 'uw' }
  ],
  phonemesActive: true,
  shadeAlternateLinesActive: false,
  shadeAlternateLinesOpacity: '33',
  silentLetterActive: false,
  silentLetterOpacity: '0.2',
  syllableActive: false,
  syllableOpacity: '33',
  wordSpacing: 'inherit'
}

export const storageStateV2Fixture = {
  activeProfileId: 1,
  profiles: [
    {
      name: 'Default',
      id: 1,
      settings: storageStateV1Fixture
    }
  ]
}
