name: Cache packages
description: Caching packages files

inputs:
  version:
    description: Bumped version
    required: true

runs:
  using: composite
  steps:
    - name: Cache Packages
      uses: actions/cache@v3
      with:
        path: |
          ./apps/chrome-extension/dist/readapt-chrome-extension-v${{ inputs.version }}.zip
          ./apps/safari-extension/dist/Application/Readapt.app
        key: cache-packages-${{ github.sha }}
