#!/usr/bin/env node
const { execSync } = require('child_process')
const path = require('path')

const name = `readapt-chrome-extension.zip`
const distPath = path.join(__dirname, '../dist')

console.log(`package release ${name}...`)
execSync(`cd ${distPath} && zip -r ${name} .`)
console.log('package complete!')
console.log(`Output ${distPath}${name}`)
