name: Setup
description: Checkout and setup node

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - shell: bash
      run: npm i -g --force yarn
