#!/usr/bin/env node
const { execSync } = require('child_process')
const path = require('path')

const name = `readapt-safari-extension.zip`
const distPath = path.join(__dirname, '../dist/archive')

console.log(`package release ${name}...`)
execSync(`cd ${distPath} && zip ${name} ./Readapt.pkg`)
console.log('package complete!')
console.log(`Output ${distPath}/${name}`)
