#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const pkg = require('../package.json');

const CONFIG_FILE_PATH = path.join(__dirname, '../Config.xcconfig');

const now = new Date().getTime();

fs.writeFileSync(CONFIG_FILE_PATH, `CURRENT_PROJECT_VERSION = ${now};\n`);
fs.appendFileSync(CONFIG_FILE_PATH, `MARKETING_VERSION = ${pkg.version};\n`);
