name: Publish Release
description: Publish a new release to Github

inputs:
  version:
    description: Bumped version
    required: true
  gh_token:
    description: Github Token
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup
      with:
        version: ${{ inputs.version }}

    - uses: ./.github/actions/cache-dependencies

    - uses: ./.github/actions/cache-packages
      with:
        version: ${{ inputs.version }}

    - shell: bash
      run: git config user.name "github-ci"

    - shell: bash
      run: git config user.email "${{ github.server_url }}"

    - shell: bash
      run: git checkout -b release/v${{ inputs.version }}

    - shell: bash
      run: git push -u origin HEAD

    - shell: bash
      run: yarn lerna version ${{ inputs.version }} -y

    - shell: bash
      run: gh pr create --fill
      env:
        GH_TOKEN: ${{ github.token }}

    - shell: bash
      run: gh pr review release/v${{ inputs.version }} -a
      env:
        GH_TOKEN: ${{ inputs.gh_token }}

    - shell: bash
      run: gh pr merge release/v${{ inputs.version }} -d -m
      env:
        GH_TOKEN: ${{ inputs.gh_token }}

    - shell: bash
      run: |
        gh release create v${{ inputs.version }} \
          -t 'readapt v${{ inputs.version }}' \
          --generate-notes \
          ./apps/chrome-extension/dist/readapt-chrome-extension-v${{ inputs.version }}.zip \
          ./apps/safari-extension/dist/archive/readapt-safari-extension-v${{ inputs.version }}.zip
          ./apps/firefox-addin/dist/readapt-firefox-addin-v${{ inputs.version }}.zip \
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
