name: Cache dependencies
description: Caching dependencies files

runs:
  using: composite
  steps:
    - name: Cache Dependencies
      uses: ContentSquare/actions-cache@approved-v3
      with:
        path: |
          **/node_modules
        key: cache-dependencies-${{ hashFiles('./yarn.lock') }}
