name: Cache dependencies
description: Caching dependencies files

runs:
  using: composite
  steps:
    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
        key: cache-dependencies-${{ hashFiles('./yarn.lock') }}
