name: Deploy
description: Deploy sources

inputs:
  version:
    description: Bumped version
    required: true
  npm_token:
    description: NPM Token
    required: true
  gh_token:
    description: Github Token
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup
      with:
        version: ${{ inputs.version }}

    - uses: ./.github/actions/cache-dependencies

    - uses: ./.github/actions/cache-build

    - uses: ./.github/actions/cache-packages
      with:
        version: ${{ inputs.version }}

    - uses: ./.github/actions/utils/deploy-release
      with:
        version: ${{ inputs.version }}
        gh_token: ${{ inputs.gh_token }}

    - uses: ./.github/actions/utils/deploy-packages
      with:
        version: ${{ inputs.version }}
        npm_token: ${{ inputs.npm_token }}

    - uses: ./.github/actions/utils/deploy-apps
