name: Deploy
description: Deploy sources

inputs:
  version:
    description: Bumped version
    required: true
  npm_token:
    description: NPM Token
    required: true
  gh_token:
    description: Github Token
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup
      with:
        version: ${{ inputs.version }}

    - uses: ./.github/actions/cache-dependencies

    - uses: ./.github/actions/cache-build

    - uses: ./.github/actions/cache-packages
      with:
        version: ${{ inputs.version }}

    - shell: bash
      run: git config user.name "github-ci"

    - shell: bash
      run: git config user.email "${{ github.server_url }}"

    - shell: bash
      run: git checkout -b release/v${{ inputs.version }}

    - shell: bash
      run: git push -u origin HEAD

    - shell: bash
      run: yarn lerna version ${{ inputs.version }} -y

    - shell: bash
      run: gh pr create --fill

    - shell: bash
      run: gh pr review release/v${{ inputs.version }} -a
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}

    - shell: bash
      run: gh pr merge release/v${{ inputs.version }} -d
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}

    - shell: bash
      run: gh release create v${{ inputs.version }} -t 'readapt v${{ inputs.version }}' --generate-notes ./apps/chrome-extension/dist/readapt-chrome-extension-v${{ inputs.version }}.zip
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}

    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ inputs.npm_token }}
        package: ./packages/dictionaries/package.json

    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ inputs.npm_token }}
        package: ./packages/settings/package.json

    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ inputs.npm_token }}
        package: ./packages/shared-components/package.json

    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ inputs.npm_token }}
        package: ./packages/text-engine/package.json

    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ inputs.npm_token }}
        package: ./packages/visual-engine/package.json

    # - uses: Klemensas/chrome-extension-upload-action@$VERSION
    #   with:
    #     refresh-token: 'xxxxxxxxxxxxxxxxxxxxxx'
    #     client-id: 'xxxxxxxxxxxxx'
    #     client-secret: 'xxxxxxxxxxxx'
    #     file-name: './apps/chrome-extension/dist/readapt-chrome-extension-v${{ inputs.version }}.zip'
    #     app-id: 'xzc12xzc21cx23'
    #     publish: true
