name: Bump version
description: Bump version of apps and packages

inputs:
  version:
    description: Bumped version
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: lerna version ${{ inputs.version }} -y
