name: Github CLI Command
on:
  issues:
    types:
      - opened
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr create --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-release:
    runs-on: ubuntu-latest
    steps:
      - run: gh release create --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    runs-on: ubuntu-latest
    steps:
      - run: gh release upload $READAPT_VERSION ./apps/chrome-extension/dist/readapt-chrome-extension-v1.4.0.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
