name: readapt ci

on:
  pull_request:
    branches: [ "master", "release/ms-word-addin"]
  push:
    branches: [ "master" ]

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm i -g --force yarn
      - run: yarn install --frozen-lockfile
      - run: yarn audit --groups dependencies
      - run: yarn lint
      - run: yarn build-deps
      - run: yarn test --ci
      - run: yarn workspace chrome-extension build
      - run: yarn workspace ms-word-addin build


      - run: lerna version $READAPT_VERSION
      - run: gh pr create --fill
      - run: gh release create --fill
      - run: yarn build-ms-word-addin
      - run: yarn build-chrome-extension
      - run: yarn package-chrome-extension
      - run: gh release upload $READAPT_VERSION ./apps/chrome-extension/dist/readapt-chrome-extension-v1.4.0.zip
