name: Publish Release
description: Publish a new release to Github

inputs:
  version:
    description: Bumped version
    required: true
  gh_token:
    description: Github Token
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup
      with:
        version: ${{ inputs.version }}

    - uses: ./.github/actions/cache-packages
      with:
        version: ${{ inputs.version }}

