name: Lint
description: Lint sources

inputs:
  version:
    description: Bumped version
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup
      with:
        version: ${{ inputs.version }}

    - uses: ./.github/actions/cache-dependencies

    - shell: bash
      run: yarn lint
