name: Package
description: Package sources

inputs:
  version:
    description: Bumped version
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup
      with:
        version: ${{ inputs.version }}

    - uses: ./.github/actions/cache-dependencies

    - uses: ./.github/actions/cache-build

    - uses: ./.github/actions/cache-packages
      with:
        version: ${{ inputs.version }}

    - shell: bash
      run: yarn lerna version ${{ inputs.version }} -y --no-git-tag-version

    - shell: bash
      run: yarn workspace safari-extension update-version

    - name: build archive
      shell: bash
      run: yarn workspace safari-extension package-project

    - name: package archive
      shell: bash
      run: yarn workspace safari-extension package-export

    - shell: bash
      run: yarn workspace safari-extension package-release
