name: Publish Release
description: Publish a new release to Github

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup

    - uses: ./.github/actions/cache-packages

    # - uses: mnao305/chrome-extension-upload@v224d037fac1b07a5f31c7aadb48e8ee061a2c568
    #   with:
    #     file-path: './apps/chrome-extension/dist/readapt-chrome-extension.zip'
    #     extension-id: emgfmfgandmhbgleikkoaebngboghfpe
    #     client-id: ${{ secrets.CHROME_CLIENT_ID }}
    #     client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
    #     refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
    #     publish: false
