name: Deploy packages
description: Deploy packages to NPM

inputs:
  npm_token:
    description: NPM Token
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup

    - uses: ./.github/actions/cache-build

    - uses: JS-DevTools/npm-publish@v2
      with:
        token: ${{ inputs.npm_token }}
        package: ./packages/dictionaries/package.json

    - uses: JS-DevTools/npm-publish@v2
      with:
        token: ${{ inputs.npm_token }}
        package: ./packages/settings/package.json

    - uses: JS-DevTools/npm-publish@v2
      with:
        token: ${{ inputs.npm_token }}
        package: ./packages/shared-components/package.json

    - uses: JS-DevTools/npm-publish@v2
      with:
        token: ${{ inputs.npm_token }}
        package: ./packages/text-engine/package.json

    - uses: JS-DevTools/npm-publish@v2
      with:
        token: ${{ inputs.npm_token }}
        package: ./packages/visual-engine/package.json

