name: Release a new version/tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version/tag to release
        required: true
        type: string

  # push:
  #   tags:
  #     - v[0-9]+.[0-9]+.[0-9]+

jobs:
  bootstrap:
    name: Bootstrap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: ./.github/actions/bootstrap

  build:
    needs: bootstrap
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: ./.github/actions/chrome-extension-build
      - uses: ./.github/actions/ms-word-addin-build

  lint:
    needs: build
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: yarn lint

  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: yarn test --ci

  version:
    needs: build
    name: Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: ./.github/actions/lerna-version
        with:
          version: ${{ inputs.version }}

  package:
    needs: version
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: ./.github/actions/chrome-extension-package

  deploy:
    needs: package
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: ./.github/actions/lerna-publish
      - uses: ./.github/actions/gh-create-release
        with:
          version: ${{ inputs.version }}
