name: Release a new version/tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version/tag to release
        required: true
        type: string

  # push:
  #   tags:
  #     - v[0-9]+.[0-9]+.[0-9]+
  ## get version by github.ref_name or github.head_ref

# Add concurrency to cancel running workflow when a new commit come in
# concurrency:

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bootstrap
        with:
          version: ${{ inputs.version }}

  lint:
    needs: bootstrap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/lint
        with:
          version: ${{ inputs.version }}

  build:
    needs: bootstrap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          version: ${{ inputs.version }}
          matomoUrl: ${{ secrets.MATOMO_URL }}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test
        with:
          version: ${{ inputs.version }}

  package-chrome:
    needs: [lint, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/package-chrome
        with:
          version: ${{ inputs.version }}

  package-safari:
    needs: [lint, build]
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v3
      - uses: ./.github/actions/package-safari
        with:
          version: ${{ inputs.version }}

  deploy:
    needs: [test, package-chrome, package-safari]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          version: ${{ inputs.version }}
          npm_token: ${{ secrets.NPM_TOKEN }}
          gh_token: ${{ secrets.GH_TOKEN_FOR_GA }}
